/**
 * Central registry of brand asset paths (served from /public).
 * Swap a path here and every component picks it up.
 */

/** srcset for resized copies generated by `npm run images` (resize only — see scripts/optimize-images.mjs) */
const optimizedSrcSet = (name: string, widths: number[]) =>
  widths.map((w) => `/assets/images/optimized/${name}-${w}.webp ${w}w`).join(', ');

export const assets = {
  logo: {
    // Supplied logo is a JPG. Replace with a PNG/SVG master when available.
    src: '/assets/images/bsa-logo.jpg',
    width: 447,
    height: 447,
  },
  portrait: {
    primary: {
      // Transparent cut-out supplied by the client
      src: '/assets/images/booda-sunday-adeyemo.png',
      width: 1024,
      height: 1536,
      srcSet: optimizedSrcSet('booda-sunday-adeyemo', [480, 800, 1024]),
    },
    alternate: {
      // White outfit, opaque studio backdrop (photographer watermark retained)
      src: '/assets/images/booda-sunday-adeyemo-white.png',
      width: 1200,
      height: 1800,
      srcSet: optimizedSrcSet('booda-sunday-adeyemo-white', [480, 800, 1200]),
    },
    /** 2026 Independence shoot; web copies in /portraits (see scripts/optimize-images.mjs) */
    independenceCutout: {
      // Transparent cut-out, sky-blue kaftan (About hero)
      src: '/assets/images/portraits/independence-2026-23.png',
      width: 1056,
      height: 1490,
      srcSet: [480, 800, 1056]
        .map((w) => `/assets/images/portraits/independence-2026-23-${w}.webp ${w}w`)
        .join(', '),
    },
    independenceDesk: {
      // Seated at a desk with the Nigerian flag; photographer watermark top right
      src: '/assets/images/portraits/independence-2026-12.jpg',
      width: 1400,
      height: 2026,
      srcSet: [640, 1000, 1400]
        .map((w) => `/assets/images/portraits/independence-2026-12-${w}.webp ${w}w`)
        .join(', '),
    },
  },
  video: {
    // H.264 High + AAC, 1280×720 (16:9), 1:54, moov at start (streams progressively)
    campaignMessage: '/assets/videos/campaign-message.mp4',
  },
  projects: {
    communityOutreach: {
      src: '/assets/images/community-outreach-1.jpg',
      width: 2048,
      height: 1536,
      srcSet: optimizedSrcSet('community-outreach-1', [640, 1000, 1400]),
    },
    campaign: {
      // Carries a baked-in "BSA Foundation — Commissioning of Ojude Ajaawa Borehole" caption
      src: '/assets/images/campaign.jpg',
      width: 1944,
      height: 1296,
      srcSet: optimizedSrcSet('campaign', [640, 1000, 1400]),
    },
    cashGift: {
      src: '/assets/images/cash-gift.jpg',
      width: 2048,
      height: 1536,
      srcSet: optimizedSrcSet('cash-gift', [640, 1000, 1400]),
    },
    communityOutreach2: {
      // Portrait orientation
      src: '/assets/images/community-outreach-2.jpg',
      width: 1536,
      height: 2048,
      srcSet: optimizedSrcSet('community-outreach-2', [640, 1000, 1536]),
    },
    classroom: {
      src: '/assets/images/outreach-in-the-classroom.jpg',
      width: 2048,
      height: 1536,
      srcSet: optimizedSrcSet('outreach-in-the-classroom', [640, 1000, 1400]),
    },
    classroom2: {
      src: '/assets/images/outreach-in-the-classroom-2.jpg',
      width: 2048,
      height: 1536,
      srcSet: optimizedSrcSet('outreach-in-the-classroom-2', [640, 1000, 1400]),
    },
  },
  /**
   * TEMPORARY — these four images appear to be AI-generated (they match the
   * design mockup). Replace with real campaign photographs before launch.
   */
  movement: {
    banner: {
      // Figure on the left; the right side has a baked-in navy fade (cropped out in CSS)
      src: '/assets/images/join-the-movement.png',
      width: 2109,
      height: 745,
      srcSet: optimizedSrcSet('join-the-movement', [800, 1400, 2109]),
    },
    volunteer: {
      src: '/assets/images/volunteer-with-us.png',
      width: 1536,
      height: 1024,
      srcSet: optimizedSrcSet('volunteer-with-us', [480, 768, 1024]),
    },
    spreadTheWord: {
      src: '/assets/images/spread-the-word.png',
      width: 1536,
      height: 1024,
      srcSet: optimizedSrcSet('spread-the-word', [480, 768, 1024]),
    },
    support: {
      src: '/assets/images/support-the-campaign.png',
      width: 1536,
      height: 1024,
      srcSet: optimizedSrcSet('support-the-campaign', [480, 768, 1024]),
    },
  },
  lautechGate: {
    // LAUTECH front gate, Ogbomoso. Supplied at 547×365 (soft when shown large)
    src: '/assets/images/LAUTECH%20front%20gate.jpg',
    width: 547,
    height: 365,
  },
  community: {
    // Ogbomoso hillside landscape, used by the site-wide PageCTA
    // Aerial view over Ogbomoso. Supplied at 576×324 (soft when shown large);
    // no resized copies: a WebP version came out larger than this JPEG
    src: '/assets/images/Ogbomosho-community-view.jpg',
    width: 576,
    height: 324,
  },
  cityscape: {
    // Aerial view of an Ogbomoso road junction. Supplied at 1024×576
    src: '/assets/images/ogbomosho-city-view.jpg',
    width: 1024,
    height: 576,
    srcSet: optimizedSrcSet('ogbomosho-city-view', [640, 1024]),
  },
} as const;
