import { assets } from '@/lib/assets';
import { projectPhoto } from '@/lib/projectPhotos';
import type { GalleryCategory, GalleryItem, GalleryPhoto } from '@/types/content';

/**
 * Gallery content: local photos and YouTube videos. No CMS; edit this file.
 *
 * Add a project photo: put the original in assets-source/projects/, add it to
 * `projectPhotos` in scripts/optimize-images.mjs, run `npm run images`, then
 * add an entry here with `image: projectPhoto('<slug>', '<alt text>')`.
 * Add a campaign flyer: put the original in assets-source/campaign/, add it to
 * `campaignFlyers` in the same script, run `npm run images`, then add an entry
 * with `image: flyer('<slug>', '<alt text>')` and `fit: 'contain'`.
 * Add any other photo: put it in /public/assets/images/gallery/ and use
 * `image: { src, width, height, alt }`.
 * Add a video: add a { type: 'video', youtubeId: '...' } entry.
 * Items show in the order listed here (put the newest first).
 *
 * Titles are the campaign's project names, approved copy, or the photo's own
 * printed caption. Dates are only those stated in a project's name.
 */
/** Web copy of a campaign flyer (900×1200), generated by `npm run images`. */
const flyer = (slug: string, alt: string): GalleryPhoto['image'] => ({
  src: `/assets/images/flyers/${slug}.jpg`,
  srcSet: [600, 900].map((w) => `/assets/images/flyers/${slug}-${w}.webp ${w}w`).join(', '),
  width: 900,
  height: 1200,
  alt,
});

const items: GalleryItem[] = [
  /* Campaign flyers (supplied 1 Oct 2026). Titles are each flyer's own headline. */
  {
    id: 'flyer-new-dawn-2027',
    type: 'image',
    category: 'campaign',
    title: 'New Dawn 2027',
    fit: 'contain',
    image: flyer(
      'new-dawn-2027',
      'Campaign flyer reading New Dawn 2027: Booda Sunday Adeyemo (BSA), for the Oyo State House of Assembly, Ogbomoso South, Nigeria Democratic Congress',
    ),
  },
  {
    id: 'flyer-sure-mercy',
    type: 'image',
    category: 'campaign',
    title: 'Sure Mercy',
    fit: 'contain',
    image: flyer(
      'sure-mercy',
      'Campaign flyer reading Sure Mercy: Vote Booda Sunday Adeyemo for Member, Oyo State House of Assembly, Ogbomoso South Constituency, Nigeria Democratic Congress',
    ),
  },
  {
    id: 'flyer-our-2027-candidates',
    type: 'image',
    category: 'campaign',
    title: 'Our 2027 Candidates',
    fit: 'contain',
    image: flyer(
      'our-2027-candidates',
      'Campaign flyer reading Our 2027 Candidates, Vote NDC from top to down, showing Booda Sunday Adeyemo, Dr. Kunle Adegbite, Peter Onwubuasi Gregory Obi and Adeyinka Remi-Oluwaseun',
    ),
  },
  {
    id: 'flyer-new-dawn-2027-joint',
    type: 'image',
    category: 'campaign',
    title: 'New Dawn 2027 with Adeyinka Remi-Oluwaseun',
    fit: 'contain',
    image: flyer(
      'new-dawn-2027-joint',
      'Campaign flyer reading New Dawn 2027: Adeyinka Remi-Oluwaseun for Ogbomoso North and Booda Sunday Adeyemo (BSA) for Ogbomoso South, Oyo State House of Assembly, Nigeria Democratic Congress',
    ),
  },
  {
    id: 'flyer-new-dawn-2027-joint-2',
    type: 'image',
    category: 'campaign',
    title: 'New Dawn 2027 with Adeyinka Remi-Oluwaseun',
    fit: 'contain',
    image: flyer(
      'new-dawn-2027-joint-2',
      'Campaign flyer reading New Dawn 2027, a second design: Adeyinka Remi-Oluwaseun for Ogbomoso North and Booda Sunday Adeyemo for Ogbomoso South, Oyo State House of Assembly, Nigeria Democratic Congress',
    ),
  },

  /* Project photos (supplied 1 Oct 2026), newest dated projects first */
  {
    id: 'jamb-scholarship-2025',
    type: 'image',
    category: 'education',
    title: '2025 BSA Jamb Scholarship',
    date: '2025',
    image: projectPhoto(
      'jamb-scholarship-2025',
      'A speaker with a microphone addressing students in a classroom at the 2025 JAMB scholarship orientation',
    ),
  },
  {
    id: 'jamb-scholarship-2025-2',
    type: 'image',
    category: 'education',
    title: '2025 BSA Jamb Scholarship',
    date: '2025',
    image: projectPhoto(
      'jamb-scholarship-2025-2',
      'A man addressing students seated in a classroom at the 2025 JAMB scholarship orientation',
    ),
  },
  {
    id: 'jamb-scholarship-2025-3',
    type: 'image',
    category: 'education',
    title: '2025 BSA Jamb Scholarship',
    date: '2025',
    image: projectPhoto(
      'jamb-scholarship-2025-3',
      'Students seated in a classroom during the 2025 JAMB scholarship orientation',
    ),
  },
  {
    id: 'summit-beyond-limits',
    type: 'image',
    category: 'events',
    title: 'BSA Capacity Building Summit Beyond Limits',
    image: projectPhoto(
      'summit-beyond-limits',
      'A speaker on stage at the Capacity Building Summit, with Beyond Limits signage behind',
    ),
  },
  {
    id: 'summit-beyond-limits-2',
    type: 'image',
    category: 'events',
    title: 'BSA Capacity Building Summit Beyond Limits',
    image: projectPhoto(
      'summit-beyond-limits-2',
      'A speaker in white addressing a seated audience in a hall at the Capacity Building Summit',
    ),
  },
  {
    id: 'summit-beyond-limits-3',
    type: 'image',
    category: 'events',
    title: 'BSA Capacity Building Summit Beyond Limits',
    image: projectPhoto(
      'summit-beyond-limits-3',
      'Attendees seated in rows, taking notes at the Capacity Building Summit',
    ),
  },
  {
    id: 'jamb-scholarship-2024',
    type: 'image',
    category: 'education',
    title: '2024 BSA Jamb Scholarship',
    date: '2024',
    image: projectPhoto(
      'jamb-scholarship-2024',
      'A large group of students and guests holding up their scholarship certificates in a hall',
    ),
  },
  {
    id: 'jamb-scholarship-2024-2',
    type: 'image',
    category: 'education',
    title: '2024 BSA Jamb Scholarship',
    date: '2024',
    image: projectPhoto(
      'jamb-scholarship-2024-2',
      'Students holding up scholarship certificates in a hall, with guests seated at the front',
    ),
  },
  {
    id: 'jamb-scholarship-2024-3',
    type: 'image',
    category: 'education',
    title: '2024 BSA Jamb Scholarship',
    date: '2024',
    image: projectPhoto(
      'jamb-scholarship-2024-3',
      'A student holding a scholarship certificate, standing beside a man in a blue outfit',
    ),
  },
  {
    id: 'jamb-scholarship-2023',
    type: 'image',
    category: 'education',
    title: '2023 BSA Jamb Scholarship',
    date: '2023',
    image: projectPhoto(
      'jamb-scholarship-2023',
      'A student receiving a scholarship certificate from two men, one in a BSA T-shirt',
    ),
  },
  {
    id: 'jamb-scholarship-2023-2',
    type: 'image',
    category: 'education',
    title: '2023 BSA Jamb Scholarship',
    date: '2023',
    image: projectPhoto(
      'jamb-scholarship-2023-2',
      'A young man receiving a scholarship certificate from two men, one in a BSA T-shirt',
    ),
  },
  {
    id: 'jamb-scholarship-2023-3',
    type: 'image',
    category: 'education',
    title: '2023 BSA Jamb Scholarship',
    date: '2023',
    image: projectPhoto(
      'jamb-scholarship-2023-3',
      'Students filling in forms at a table during the scholarship presentation',
    ),
  },
  {
    id: 'christmas-love-sharing-2022',
    type: 'image',
    category: 'community-outreach',
    title: 'BSA Christmas Love Sharing 2022',
    date: '2022',
    image: projectPhoto(
      'christmas-love-sharing-2022',
      'A large crowd of residents gathered in a school compound for Christmas Love Sharing',
    ),
  },
  {
    id: 'christmas-love-sharing-2022-2',
    type: 'image',
    category: 'community-outreach',
    title: 'BSA Christmas Love Sharing 2022',
    date: '2022',
    image: projectPhoto(
      'christmas-love-sharing-2022-2',
      'Residents gathered along a school veranda for Christmas Love Sharing',
    ),
  },
  {
    id: 'christmas-love-sharing-2022-3',
    type: 'image',
    category: 'community-outreach',
    title: 'BSA Christmas Love Sharing 2022',
    date: '2022',
    image: projectPhoto(
      'christmas-love-sharing-2022-3',
      'Rows of black food bags printed Operation Feed 5000, ready for Christmas Love Sharing',
    ),
  },
  {
    id: 'eye-treatment-okada-riders',
    type: 'image',
    category: 'community-outreach',
    title: 'BSA Free Medical Eye Treatment for Okada Riders',
    image: projectPhoto(
      'eye-treatment-okada-riders',
      'A man in trial frames reading a vision test chart at the free eye treatment',
    ),
  },
  {
    id: 'eye-treatment-okada-riders-2',
    type: 'image',
    category: 'community-outreach',
    title: 'BSA Free Medical Eye Treatment for Okada Riders',
    image: projectPhoto(
      'eye-treatment-okada-riders-2',
      'A health worker fitting trial frames on a man reading a vision chart',
    ),
  },
  {
    id: 'eye-treatment-okada-riders-3',
    type: 'image',
    category: 'community-outreach',
    title: 'BSA Free Medical Eye Treatment for Okada Riders',
    image: projectPhoto(
      'eye-treatment-okada-riders-3',
      'A man having his eyes examined with a small light at the free eye treatment',
    ),
  },
  {
    id: 'okada-bus-stop-seminary',
    type: 'image',
    category: 'projects',
    title: 'BSA Construction of Okada Bustop Seminary',
    image: projectPhoto(
      'okada-bus-stop-seminary',
      'A roadside okada shelter with a BSA sign, with people seated and standing beneath it',
    ),
  },
  {
    id: 'okada-bus-stop-seminary-2',
    type: 'image',
    category: 'projects',
    title: 'BSA Construction of Okada Bustop Seminary',
    image: projectPhoto(
      'okada-bus-stop-seminary-2',
      'A dark okada shelter with a large BSA sign, seen from the roadside',
    ),
  },
  {
    id: 'okada-bus-stop-baptist-high-school',
    type: 'image',
    category: 'projects',
    title: 'Baptist High-school Construction of Okada Bustop',
    image: projectPhoto(
      'okada-bus-stop-baptist-high-school',
      'An okada shelter with benches and BSA signs, its roof marked as constructed by the Booda Sunday Adeyemo Foundation',
    ),
  },
  {
    id: 'okada-bus-stop-baptist-high-school-2',
    type: 'image',
    category: 'projects',
    title: 'Baptist High-school Construction of Okada Bustop',
    image: projectPhoto(
      'okada-bus-stop-baptist-high-school-2',
      'Another view of the okada shelter with benches and BSA signs',
    ),
  },
  {
    id: 'drainage-oluwatedo',
    type: 'image',
    category: 'projects',
    title: 'BSA Oluwatedo Community Drainage',
    image: projectPhoto(
      'drainage-oluwatedo',
      'A concrete drainage channel running alongside a wall and an unpaved road',
    ),
  },
  {
    id: 'drainage-oluwatedo-2',
    type: 'image',
    category: 'projects',
    title: 'BSA Oluwatedo Community Drainage',
    image: projectPhoto(
      'drainage-oluwatedo-2',
      'A drainage channel along an unpaved road lined with buildings',
    ),
  },
  {
    id: 'bike-riders-akomoran-empowerment',
    type: 'image',
    category: 'community-outreach',
    title: 'BSA Bike Riders Akomoran Empowerment',
    image: projectPhoto(
      'bike-riders-akomoran-empowerment',
      'Men standing beside a new motorcycle during the bike riders empowerment',
    ),
  },
  {
    id: 'bike-riders-akomoran-empowerment-2',
    type: 'image',
    category: 'community-outreach',
    title: 'BSA Bike Riders Akomoran Empowerment',
    image: projectPhoto(
      'bike-riders-akomoran-empowerment-2',
      'Men gathered around a new motorcycle during the bike riders empowerment',
    ),
  },
  {
    id: 'bike-riders-akomoran-empowerment-3',
    type: 'image',
    category: 'community-outreach',
    title: 'BSA Bike Riders Akomoran Empowerment',
    image: projectPhoto(
      'bike-riders-akomoran-empowerment-3',
      'A man working on motorcycle parts in a workshop surrounded by motorcycles',
    ),
  },
  {
    id: 'christmas-love-extension',
    type: 'image',
    category: 'community-outreach',
    title: 'BSA Christmas Love Extension',
    image: projectPhoto(
      'christmas-love-extension',
      'A man in a BSA jacket speaking into a microphone beside rows of gift bags',
    ),
  },
  {
    id: 'christmas-love-extension-2',
    type: 'image',
    category: 'community-outreach',
    title: 'BSA Christmas Love Extension',
    image: projectPhoto(
      'christmas-love-extension-2',
      'Gift bags lined up on the floor beneath a handwritten sign',
    ),
  },
  {
    id: 'less-privileged',
    type: 'image',
    category: 'community-outreach',
    title: 'BSA to the Less Privilege',
    image: projectPhoto(
      'less-privileged',
      'A smiling young man holding up a BSA bag beside sacks of food',
    ),
  },
  {
    id: 'less-privileged-2',
    type: 'image',
    category: 'community-outreach',
    title: 'BSA to the Less Privilege',
    image: projectPhoto(
      'less-privileged-2',
      'A man speaking with a crowd of women gathered outdoors',
    ),
  },
  {
    id: 'widows-cash-empowerment',
    type: 'image',
    category: 'community-outreach',
    title: 'BSA Widows Cash Empowerment',
    image: projectPhoto(
      'widows-cash-empowerment',
      'Women seated together in a hall at the widows cash empowerment',
    ),
  },
  {
    id: 'widows-cash-empowerment-2',
    type: 'image',
    category: 'community-outreach',
    title: 'BSA Widows Cash Empowerment',
    image: projectPhoto(
      'widows-cash-empowerment-2',
      'A speaker with a microphone addressing women seated in a hall',
    ),
  },
  {
    id: 'widows-cash-empowerment-3',
    type: 'image',
    category: 'community-outreach',
    title: 'BSA Widows Cash Empowerment',
    image: projectPhoto(
      'widows-cash-empowerment-3',
      'Women seated together, listening during the widows cash empowerment',
    ),
  },
  {
    id: 'borehole-ojude-ajaawa',
    type: 'image',
    category: 'projects',
    title: 'Commissioning of Ojude Ajaawa Borehole',
    image: projectPhoto(
      'borehole-ojude-ajaawa',
      'Residents gathered along a street in Ojude Ajaawa for the borehole commissioning',
    ),
  },
  {
    id: 'borehole-akunko-junction-isoko',
    type: 'image',
    category: 'projects',
    title: 'BSA Borehole Commissioning Akunko Junction Isoko',
    image: projectPhoto(
      'borehole-akunko-junction-isoko',
      'Residents gathered in front of a borehole with two water tanks, marked as renovated by the Booda Sunday Adeyemo Foundation',
    ),
  },
  {
    id: 'bus-stop-arowomole',
    type: 'image',
    category: 'projects',
    title: 'Commissioning of BSA Arowomole Bus Stop',
    image: projectPhoto(
      'bus-stop-arowomole',
      'Residents gathered at the commissioning of the BSA Arowomole Bus Stop',
    ),
  },
  {
    id: 'bus-stop-arowomole-2',
    type: 'image',
    category: 'projects',
    title: 'Commissioning of BSA Arowomole Bus Stop',
    image: projectPhoto(
      'bus-stop-arowomole-2',
      'The BSA Arowomole Bus Stop with a ribbon across the front and women standing nearby',
    ),
  },
  {
    id: 'covid-19-palliatives',
    type: 'image',
    category: 'community-outreach',
    title: 'Palliative for Ogbomosho South During Covid 19',
    image: projectPhoto(
      'covid-19-palliatives',
      'A masked volunteer handing a relief package to a woman during the COVID-19 palliative distribution',
    ),
  },
  {
    id: 'covid-19-palliatives-2',
    type: 'image',
    category: 'community-outreach',
    title: 'Palliative for Ogbomosho South During Covid 19',
    image: projectPhoto(
      'covid-19-palliatives-2',
      'A masked volunteer handing a relief package to a young woman during the COVID-19 palliative distribution',
    ),
  },
  {
    id: 'operation-feed-the-needy',
    type: 'image',
    category: 'community-outreach',
    title: 'BSA Operation Feed the Needy',
    image: projectPhoto(
      'operation-feed-the-needy',
      'A ribbon-cutting behind a row of food bags at Operation Feed the Needy',
    ),
  },
  {
    id: 'operation-feed-the-needy-2',
    type: 'image',
    category: 'community-outreach',
    title: 'BSA Operation Feed the Needy',
    image: projectPhoto(
      'operation-feed-the-needy-2',
      'A collage of volunteers and recipients with food packages at Operation Feed the Needy',
    ),
  },
  {
    id: 'majokosile-graduation',
    type: 'image',
    category: 'events',
    title: 'BSA Majokosile Graduation',
    image: projectPhoto(
      'majokosile-graduation',
      'Women arranging handbags on a table at the Majokosile graduation',
    ),
  },
  {
    id: 'majokosile-graduation-2',
    type: 'image',
    category: 'events',
    title: 'BSA Majokosile Graduation',
    image: projectPhoto(
      'majokosile-graduation-2',
      'Men looking at a display of handmade bags at the Majokosile graduation',
    ),
  },
  {
    id: 'majokosile-graduation-3',
    type: 'image',
    category: 'events',
    title: 'BSA Majokosile Graduation',
    image: projectPhoto(
      'majokosile-graduation-3',
      'A woman seated in front of a display of handmade garments at the Majokosile graduation',
    ),
  },

  /* Earlier campaign photos */
  {
    id: 'community-outreach-01',
    type: 'image',
    category: 'community-outreach',
    title: 'Supporting families across Ogbomoso South',
    featured: true,
    image: {
      ...assets.projects.communityOutreach,
      alt: 'Women from the community seated together at a community outreach gathering',
      position: '50% 55%',
    },
  },
  {
    id: 'ojude-ajaawa-borehole',
    type: 'image',
    category: 'projects',
    // From the caption printed on the photograph
    title: 'Commissioning of Ojude Ajaawa Borehole',
    fromTheCampaign: true,
    image: {
      ...assets.projects.campaign,
      alt: 'Booda Sunday Adeyemo speaking through a megaphone at a BSA Foundation borehole commissioning',
      position: '55% 30%',
    },
  },
  {
    id: 'cash-gift-students',
    type: 'image',
    category: 'education',
    title: 'Cash gifts to support students',
    fromTheCampaign: true,
    image: {
      ...assets.projects.cashGift,
      alt: 'Booda Sunday Adeyemo presenting a BSA Foundation scholarship cheque to a student',
      position: '30% 40%',
    },
  },
  {
    id: 'classroom-outreach-01',
    type: 'image',
    category: 'education',
    title: 'Outreach in the classroom',
    image: {
      ...assets.projects.classroom,
      alt: 'A teacher addressing a classroom of students with open textbooks',
      position: '40% 45%',
    },
  },
  {
    id: 'classroom-outreach-02',
    type: 'image',
    category: 'education',
    title: 'Students in class',
    image: {
      ...assets.projects.classroom2,
      alt: 'Students in school uniform working through exam papers at their desks',
      position: '50% 40%',
    },
  },
  {
    id: 'residents-gathering',
    type: 'image',
    category: 'campaign',
    title: 'Engaging with our people',
    fromTheCampaign: true,
    image: {
      ...assets.projects.communityOutreach2,
      alt: 'Residents gathered outdoors listening to a speaker',
      position: '50% 25%',
    },
  },
  {
    // DEMO — fake ID so the video player can be tested. Development only;
    // delete once a real campaign video is added.
    id: 'demo-video',
    type: 'video',
    category: 'events',
    title: 'Demo video (replace with a campaign YouTube video)',
    youtubeId: 'YOUTUBE_VIDEO_ID',
    placeholder: true,
    thumbnail: { ...assets.community, alt: '', position: '50% 60%' },
  },
];

/** Published items: demo placeholders are dropped from production builds. */
export const galleryItems: GalleryItem[] = items.filter(
  (item) => import.meta.env.DEV || !(item.type === 'video' && item.placeholder),
);

export const galleryCategoryLabels: Record<GalleryCategory, string> = {
  campaign: 'Campaign',
  'community-outreach': 'Community Outreach',
  events: 'Events',
  projects: 'Projects',
  education: 'Education',
};

/** Filter row. "videos" matches every video regardless of category. */
export const galleryFilters = [
  { value: 'all', label: 'All' },
  { value: 'campaign', label: 'Campaign' },
  { value: 'community-outreach', label: 'Community Outreach' },
  { value: 'events', label: 'Events' },
  { value: 'projects', label: 'Projects' },
  { value: 'education', label: 'Education' },
  { value: 'videos', label: 'Videos' },
] as const;

export type GalleryFilter = (typeof galleryFilters)[number]['value'];

export const galleryPage = {
  seo: {
    title: 'Gallery',
    description:
      'Photos and videos from community activities, outreach programmes, events and campaign engagements across Ogbomoso South.',
  },
  hero: {
    eyebrow: 'Campaign Gallery',
    heading: { lead: 'Moments from the', highlight: 'ground.' },
    subtitle:
      'Photos and videos from community activities, outreach programmes, events and campaign engagements across Ogbomoso South.',
    image: { ...assets.projects.classroom, alt: '', position: '40% 40%' },
  },
  /** Items revealed per "Load more" */
  pageSize: 12,
  emptyMessage: 'No gallery items in this category yet.',
  fromTheCampaign: { heading: 'From the campaign' },
  cta: {
    eyebrow: '',
    title: 'See the work behind the campaign.',
    highlight: '',
    description:
      'Explore the projects, programmes and community work happening across Ogbomoso South.',
    buttonText: 'Explore Community Impact',
    buttonHref: '/projects',
  },
};
